// Shared by client generation and the schema coverage test. path, label, kind, help, bounds.
export const GROUPS = [
  ['基本策略', [
    ['enabled', '启用压缩优化', 'boolean', '仅处理摘要压缩；普通对话和标题沿用宿主配置。'],
    ['matchAll', '适用于所有模型', 'boolean', '关闭后仅处理下面列表中的模型。'],
    ['models', '模型 ID 列表', 'list', '逗号分隔。列表为空且未启用所有模型时，不处理任何模型。'],
    ['effort', '压缩推理强度', 'text', '默认 off；只使用当前模型声明支持的值。off 不可用时选择 none/minimal/low，均不支持则沿用适配器默认。'],
    ['maxTokensFloor', '单次摘要输出预算', 'number', '默认 8192；受模型策略的输出上限和可用窗口约束。', 0, 262144],
    ['sampling.temperature', '摘要 temperature', 'optionalNumber', '留空沿用提供者默认；推理模型建议留空。', 0, 2],
    ['summaryRoute.provider', '独立摘要 provider', 'text', '与 model 一起填写；都留空则使用本次宿主压缩调用的模型。'],
    ['summaryRoute.model', '独立摘要 model', 'text', '可选择更擅长摘要或上下文更大的模型；必须已在宿主中配置。'],
  ]],
  ['窗口与安全预算', [
    ['chunking.contextWindows', '模型窗口覆盖', 'jsonObject', '总窗口（输入+输出）。JSON 示例：{"provider/model": 131072}；provider/model 优先于 model；留 {} 使用宿主声明。'],
    ['chunking.fallbackWindow', '未知模型保守窗口', 'number', '仅当宿主没有模型窗口且无手工覆盖时使用，同时写入诊断日志。', 1024, 10000000],
    ['chunking.chunkRatio', '输入预算占窗口比例', 'number', '默认 0.65；实际预算还会扣除输出和安全余量，取较小值。', 0.1, 0.95],
    ['chunking.headroomTokens', '固定安全余量 tokens', 'number', '与比例余量取较大值，预留协议封装及估算误差空间。', 0, 1000000],
    ['chunking.safetyRatio', '比例安全余量', 'number', '默认 0.1，即窗口的 10%。', 0, 0.5],
    ['chunking.tokenSafetyFactor', 'token 估算安全系数', 'number', '中英文分别估算后乘此系数；频繁出现真实超窗时可提高。', 1, 4],
    ['chunking.maxOutputTokens', '模型输出硬上限', 'number', '请按实际模型配置；不是提供者默认最大输出的预留值。', 128, 262144],
  ]],
  ['分片与最近消息', [
    ['chunking.enabled', '启用超长历史分片', 'boolean', '单条超大消息完整分段；按顺序提取，再分层合并。'],
    ['chunking.chunkMaxTokens', '每片摘要输出 tokens', 'number', '默认 2048，较小的局部摘要有助于合并收敛。', 128, 262144],
    ['chunking.mergeMaxTokens', '最终合并输出 tokens', 'number', '必须足以覆盖当前工作状态，过大会挤占输入预算。', 128, 262144],
    ['chunking.keepRecentMessages', '保留到最终合并的最近条数', 'number', '0 关闭。指原文进入最终合并，不保证最终摘要逐字保留。', 0, 1000],
    ['chunking.keepRecentTokens', '最近消息原文 token 上限', 'number', '同时受最终输入预算的 1/4 限制；超限消息正常分片提取，不丢弃。', 0, 1000000],
    ['chunking.maxChunks', '最大片数', 'number', '超过限制会明确失败，原始会话保持。', 1, 4096],
    ['chunking.maxMergeRounds', '最大合并轮数', 'number', '每轮必须变短；不收敛即停止。', 1, 32],
  ]],
  ['预处理与摘要提示', [
    ['slimOversized', '启用摘要输入预处理', 'boolean', '仅在临时摘要输入中处理思考与工具内容，磁盘事件不变。'],
    ['preprocessing.dropReasoning', '省略历史思考块', 'boolean', '保留对话、工具操作和结果；通常无需再总结旧推理轨迹。'],
    ['preprocessing.maxToolArgumentChars', '工具参数保留字符数', 'number', '首尾摘取并标记原文仍在会话日志；0 不截断。', 0, 1000000],
    ['preprocessing.maxToolResultChars', '工具结果保留字符数', 'number', '首尾摘取；0 不截断。长篇重要工具输出可关闭截断。', 0, 1000000],
    ['supplementOn', '启用补充摘要要求', 'boolean', '最终检查点仍遵循宿主传入的主压缩指令。'],
    ['supplement', '补充摘要要求', 'multiline', '追加到最终摘要指令；可指定语言、保留重点和输出风格。'],
  ]],
  ['超时与重试', [
    ['chunking.retries', '每阶段恢复重试数', 'number', '仅重试可恢复错误；超窗会缩片，截断会在安全预算内增加输出。', 0, 8],
    ['chunking.timeoutMs', '单次模型超时 ms', 'number', '超时后停止等待，取消信号传递到宿主适配器。', 100, 3600000],
    ['chunking.totalTimeoutMs', '整个压缩超时 ms', 'number', '限制包含分片、重试和合并的总时长。', 100, 14400000],
    ['chunking.retryDelayMs', '重试基础退避 ms', 'number', '指数退避，取消时立即结束等待。', 0, 60000],
    ['chunking.maxCalls', '每次压缩最大模型调用数', 'number', '所有重试、分片、合并共享此预算，防止无休止调用。', 1, 8192],
  ]],
  ['手动命令与自动兜底', [
    ['command.enabled', '启用 /gateway-compact', 'boolean', '使用宿主压缩事务，原始事件仍可回查。'],
    ['command.newContext.enabled', '启用 /clear-context', 'boolean', '硬重置会直接清除模型可见历史，不生成摘要；默认关闭。'],
    ['autoCompaction.enabled', '无内置引擎时自动兜底', 'boolean', '已有内置压缩引擎的 preset 继续由其触发；本插件仅优化摘要调用。'],
    ['autoCompaction.thresholdRatio', '自动触发比例', 'number', '仅控制无内置引擎的兜底；有内置引擎时请在该引擎配置触发阈值。', 0.1, 0.95],
    ['autoCompaction.retainTokens', '压缩后保留原文 tokens', 'optionalNumber', '宿主事务保留的尾部预算；留空使用 retainRatio。与分片合并的临时尾部不同。', 0, 1000000],
    ['autoCompaction.retainRatio', '压缩后保留原文比例', 'optionalNumber', 'retainTokens 未填写时生效；都留空使用宿主默认。', 0, 0.8],
    ['autoCompaction.headroomTokens', '自动触发安全余量', 'number', '宿主压力预算保留的额外 tokens。', 0, 1000000],
    ['autoCompaction.maxTokens', '事务摘要请求预算', 'number', '传入官方事务的输出预算；实际摘要还受上述输出策略约束。', 128, 262144],
    ['autoCompaction.compactionRetries', '仍超阈值时追加压缩数', 'number', '防止一次摘要后上下文仍过大；0 不追加。', 0, 8],
    ['autoCompaction.maxOverflowRetries', '溢出恢复重试数', 'number', '仅在压缩确实改变会话表面后重试原请求。', 0, 8],
    ['autoCompaction.summarizationProvider', '兜底事务摘要 provider', 'text', '与 model 一起填写；通常使用上面的统一独立摘要路由即可。'],
    ['autoCompaction.summarizationModel', '兜底事务摘要 model', 'text', '留空继承会话模型；统一独立摘要路由优先。'],
  ]],
];
