// Generate client.js from src/client.js (template) + ui-fields.js (single source
// of field definitions), then enforce the classic-script product gates:
// __ModuleLoader__ + plugin id present, no top-level import/export, parses as a
// classic script. Run: node scripts/build-client.mjs
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { GROUPS } from '../ui-fields.js';

for (const group of GROUPS) {
  if (!Array.isArray(group) || group.length !== 4) throw new Error('build-client: every group must be [title, badge, summary, fields]');
  for (const field of group[3]) {
    if (!Array.isArray(field) || field.length < 4 || typeof field[0] !== 'string') throw new Error(`build-client: bad field ${JSON.stringify(field)}`);
  }
}
const source = fs.readFileSync(new URL('../src/client.js', import.meta.url), 'utf8');
if (!source.includes('/* FIELD_DEFINITIONS */')) throw new Error('build-client: src/client.js lost its /* FIELD_DEFINITIONS */ placeholder');
const banner = '/* Generated by scripts/build-client.mjs from src/client.js + ui-fields.js — edit those files, not this one. */\n';
const output = banner + source.replace('/* FIELD_DEFINITIONS */', `const GROUPS = ${JSON.stringify(GROUPS)};`);
const target = fileURLToPath(new URL('../client.js', import.meta.url));
fs.writeFileSync(target, output);
if (!output.includes('__ModuleLoader__')) throw new Error('build-client: output is missing __ModuleLoader__');
if (!output.includes("id: 'dsh-gateway-compaction'")) throw new Error('build-client: output is missing the plugin id');
if (/^\s*(import|export)\s/m.test(output)) throw new Error('build-client: output has a top-level import/export; the client must be a classic script');
execFileSync(process.execPath, ['--check', target]);
const fields = GROUPS.reduce((n, g) => n + g[3].length, 0);
console.log(`build-client: client.js written (${output.length} bytes, ${GROUPS.length} groups, ${fields} fields) and gates passed`);
